#:kivy 2.3.1

<WelcomeScreen>:
    name: 'welcome_screen'
    BoxLayout:
        orientation: 'vertical'
        spacing: 20
        padding: 50
        Label:
            text: 'Welcome to Guess The Number!'
            font_size: 32
            size_hint_y: None
            height: self.texture_size[1]
        Button:
            text: 'Start Game'
            font_size: 24
            size_hint_y: None
            height: 50
            on_press: root.start_game()